name: 🧪 Test + Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📅 Checkout repo
      uses: actions/checkout@v3

    - name: 🚀 Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: 🔢 Set environment variables
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=eu-north-1" >> $GITHUB_ENV

    - name: 🔮 Run Unit Tests
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: |
        python -m unittest discover -s tests -v

    - name: 📁 Zip, Upload to S3 & Deploy Lambdas
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_ARTIFACT_BUCKET: ${{ secrets.S3_ARTIFACT_BUCKET }}
      run: |
        COMMIT=$(git rev-parse --short HEAD)
        BRANCH=$(git rev-parse --abbrev-ref HEAD)

        for fn in lambda_functions/*; do
          name=$(basename "$fn")

          # 🚫 Skip non-deployable dirs
          if [[ "$name" == "dev-notes" || ! -d "$fn" ]]; then
            echo "⏭️ Skipping $name"
            continue
          fi

          # 📦 Ensure .py files exist
          py_files=($fn/*.py)
          if [ ! -f "${py_files[0]}" ]; then
            echo "⚠️ No .py files in $name – skipping"
            continue
          fi

          zip -r "${name}.zip" "$fn"

          # ☁️ Upload to S3 for traceability
          aws s3 cp "${name}.zip" "s3://$S3_ARTIFACT_BUCKET/lambdas/${name}-${COMMIT}.zip" \
            --region "$AWS_REGION"

          # 🚀 Deploy to Lambda
          aws lambda update-function-code \
            --function-name "$name" \
            --zip-file fileb://"${name}.zip" \
            --region "$AWS_REGION" || echo "❌ Failed to update $name"

          # 🕐 Wait for update to complete
          aws lambda wait function-updated \
            --function-name "$name" \
            --region "$AWS_REGION"
        done

    - name: 📢 Notify via SNS – ✅ Success
      if: success()
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
      run: |
        COMMIT=$(git rev-parse --short HEAD)
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        aws sns publish \
          --topic-arn "$SNS_TOPIC_ARN" \
          --region "$AWS_REGION" \
          --message "✅ Lambda backend deployed successfully 🚀
          Branch: $BRANCH
          Commit: $COMMIT"

    - name: 📢 Notify via SNS – ❌ Failure
      if: failure()
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
      run: |
        COMMIT=$(git rev-parse --short HEAD)
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        aws sns publish \
          --topic-arn "$SNS_TOPIC_ARN" \
          --region "$AWS_REGION" \
          --message "❌ Lambda backend deployment FAILED ❗
          Branch: $BRANCH
          Commit: $COMMIT
          Check logs for details."          
